from __future__ import annotations

from copy import deepcopy
from datetime import UTC, datetime
from typing import Any


def _source(
    *,
    id: str,
    title: str,
    url: str,
    type: str,
    modality: str,
    category: str,
    relevance_to_signal_engine: str,
    possible_labels_or_features: str,
    access_status: str,
    license_notes: str,
    recommended_use: str,
    limitations: str,
    downloaded_locally: bool = False,
) -> dict[str, Any]:
    return {
        "id": id,
        "title": title,
        "url": url,
        "type": type,
        "modality": modality,
        "category": category,
        "relevance_to_signal_engine": relevance_to_signal_engine,
        "possible_labels_or_features": possible_labels_or_features,
        "access_status": access_status,
        "license_notes": license_notes,
        "download_status": "not_downloaded",
        "downloaded_locally": downloaded_locally,
        "recommended_use": recommended_use,
        "limitations": limitations,
    }


NLP_RESEARCH_SOURCES: tuple[dict[str, Any], ...] = (
    _source(
        id="finbert_paper",
        title="FinBERT: Financial Sentiment Analysis with Pre-trained Language Models",
        url="https://arxiv.org/abs/1908.10063",
        type="paper",
        modality="transcript",
        category="financial_nlp",
        relevance_to_signal_engine="Strong finance-domain baseline reference for sentence-level sentiment benchmarking on financial text.",
        possible_labels_or_features="positive, negative, neutral financial sentiment",
        access_status="public",
        license_notes="Paper is public; model and downstream datasets have separate licenses.",
        recommended_use="Reference model family for optional benchmark comparisons against deterministic transcript signals.",
        limitations="Sentiment labels do not map directly to guidance change, friction, or evidence quality.",
    ),
    _source(
        id="prosus_finbert_model",
        title="ProsusAI/finbert model card",
        url="https://huggingface.co/ProsusAI/finbert",
        type="library",
        modality="transcript",
        category="financial_nlp",
        relevance_to_signal_engine="Concrete local-model candidate for optional finance-specific benchmarking when cache is already available.",
        possible_labels_or_features="financial sentiment classification pipeline",
        access_status="public",
        license_notes="Use subject to model card and underlying dataset terms.",
        recommended_use="Optional offline benchmark adapter only; not canonical scoring.",
        limitations="Model-card availability does not guarantee local model cache or fit for earnings-call Q&A nuance.",
    ),
    _source(
        id="financial_phrasebank",
        title="Financial PhraseBank",
        url="https://huggingface.co/datasets/takala/financial_phrasebank",
        type="dataset",
        modality="transcript",
        category="financial_nlp",
        relevance_to_signal_engine="Widely used sentence-level finance sentiment dataset that grounds benchmark comparisons for finance text.",
        possible_labels_or_features="positive, neutral, negative financial sentiment",
        access_status="public",
        license_notes="Dataset card should be reviewed before redistribution or bulk download.",
        recommended_use="Benchmark-only sentiment reference; useful for checking whether optional models behave sensibly on finance language.",
        limitations="Short isolated sentences are a weak proxy for multi-speaker transcript review.",
    ),
    _source(
        id="loughran_mcdonald_dictionary",
        title="Loughran-McDonald Master Dictionary",
        url="https://sraf.nd.edu/loughranmcdonald-master-dictionary/",
        type="library",
        modality="transcript",
        category="financial_nlp",
        relevance_to_signal_engine="Finance-specific lexicon reference for uncertainty and tone features without requiring black-box models.",
        possible_labels_or_features="negative, positive, uncertainty, litigious, strong_modal, weak_modal",
        access_status="public",
        license_notes="Review site terms before vendoring any dictionary files.",
        recommended_use="Lexicon reference for deterministic or weak-label experiments on earnings-call language.",
        limitations="Dictionary counts need careful context handling and can overfire on long transcripts.",
    ),
    _source(
        id="fiqa_benchmark",
        title="FiQA benchmark",
        url="https://sites.google.com/view/fiqa/",
        type="benchmark",
        modality="transcript",
        category="financial_nlp",
        relevance_to_signal_engine="Finance QA and sentiment benchmark reference for optional retrieval and finance-language experiments.",
        possible_labels_or_features="financial sentiment, question answering, ranking",
        access_status="public",
        license_notes="Benchmark access and downstream dataset terms should be reviewed case by case.",
        recommended_use="Reference only for optional finance retrieval and question-answer benchmarking.",
        limitations="FiQA is not an earnings-call review dataset and does not validate conversation-level evidence quality.",
    ),
    _source(
        id="finnli_dataset",
        title="FinNLI: Novel Dataset for Multi-Genre Financial Natural Language Inference Benchmarking",
        url="https://arxiv.org/abs/2504.16188",
        type="dataset",
        modality="transcript",
        category="financial_nlp",
        relevance_to_signal_engine="Useful for reasoning-style benchmark planning around contradiction, entailment, and guidance language review.",
        possible_labels_or_features="entailment, contradiction, neutral",
        access_status="public",
        license_notes="Check dataset release terms before local use.",
        recommended_use="Reference for optional contradiction and disclosure-consistency experiments.",
        limitations="NLI labels do not directly validate reviewer usefulness in business-conversation workflows.",
    ),
    _source(
        id="earnings_calls_analyst_decision_making",
        title="Modeling financial analysts' decision making via the pragmatics and semantics of earnings calls",
        url="https://arxiv.org/abs/1906.02868",
        type="paper",
        modality="transcript",
        category="earnings_calls",
        relevance_to_signal_engine="Directly relevant to analyst pressure, Q&A pragmatics, and post-call interpretation features.",
        possible_labels_or_features="question pragmatics, semantics, analyst behavior, forecast revision correlates",
        access_status="public",
        license_notes="Public paper.",
        recommended_use="Research reference for transcript features around analyst-management friction and Q&A pressure.",
        limitations="Research correlations are not a license to claim predictive lift in this portfolio project.",
    ),
    _source(
        id="forecasting_earnings_surprises",
        title="Forecasting Earnings Surprises from Conference Call Transcripts",
        url="https://aclanthology.org/2023.findings-acl.520/",
        type="paper",
        modality="transcript",
        category="earnings_calls",
        relevance_to_signal_engine="Strong earnings-call NLP reference tying transcript content to future surprise prediction tasks.",
        possible_labels_or_features="earnings surprise direction, transcript segmentation, finance text modeling",
        access_status="public",
        license_notes="Public paper; datasets may have separate access terms.",
        recommended_use="Research reference only for benchmark framing and task design, not for unsupported performance claims.",
        limitations="Prediction framing is narrower and higher-risk than the repo's deterministic review focus.",
    ),
    _source(
        id="predicting_corporate_risk_dialogues",
        title="Predicting Corporate Risk by Jointly Modeling Company Networks and Dialogues in Earnings Conference Calls",
        url="https://arxiv.org/abs/2206.06174",
        type="paper",
        modality="transcript",
        category="earnings_calls",
        relevance_to_signal_engine="Relevant to dialogue-aware modeling and the limits of transcript-only risk inference.",
        possible_labels_or_features="dialogue structure, corporate risk, company network context",
        access_status="public",
        license_notes="Public paper.",
        recommended_use="Reference for future optional benchmark design around dialogue structure and risk cues.",
        limitations="Modeling setup is more ambitious than the current deterministic-first architecture.",
    ),
    _source(
        id="subjective_qa",
        title="SubjECTive-QA: Measuring Subjectivity in Earnings Call Transcripts' QA Through Six-Dimensional Feature Analysis",
        url="https://arxiv.org/abs/2410.20651",
        type="paper",
        modality="transcript",
        category="earnings_calls",
        relevance_to_signal_engine="Highly aligned with bounded review cues for subjectivity, uncertainty, and question-answer quality.",
        possible_labels_or_features="subjectivity dimensions, question-answer analysis, explainable features",
        access_status="public",
        license_notes="Public paper.",
        recommended_use="Reference for future bounded QA-review taxonomies without turning subjectivity into canonical truth.",
        limitations="Published methodology still needs careful translation into reviewer-centric signals.",
    ),
    _source(
        id="ibm_earnings_call_dataset",
        title="jlh-ibm/earnings_call dataset",
        url="https://huggingface.co/datasets/jlh-ibm/earnings_call",
        type="dataset",
        modality="transcript",
        category="earnings_calls",
        relevance_to_signal_engine="Useful reference source for transcript structure and later optional finance-language benchmarking.",
        possible_labels_or_features="earnings call transcripts, Q&A sections, firm/date metadata",
        access_status="public",
        license_notes="Check dataset card and underlying transcript rights before local use.",
        recommended_use="Metadata/reference only unless licensing is explicitly acceptable for local experiments.",
        limitations="Transcript rights and reuse terms may limit direct training use.",
    ),
    _source(
        id="aiera_transcript_sentiment",
        title="Aiera/aiera-transcript-sentiment dataset",
        url="https://huggingface.co/datasets/Aiera/aiera-transcript-sentiment",
        type="dataset",
        modality="transcript",
        category="earnings_calls",
        relevance_to_signal_engine="Potential finance transcript sentiment benchmark candidate closer to earnings-call language than generic emotion corpora.",
        possible_labels_or_features="transcript sentiment labels, finance text classification",
        access_status="public",
        license_notes="Review dataset card before use.",
        recommended_use="Optional benchmark reference only; do not vendor without checking terms.",
        limitations="Sentiment labels alone still under-specify guidance change, pressure, and evidence quality.",
    ),
    _source(
        id="goemotions",
        title="GoEmotions",
        url="https://arxiv.org/abs/2005.00547",
        type="dataset",
        modality="transcript",
        category="emotion_uncertainty",
        relevance_to_signal_engine="Useful for optional fine-grained emotion benchmarking, especially as a contrast to business-domain signals.",
        possible_labels_or_features="fine-grained emotion classes, neutral",
        access_status="public",
        license_notes="Paper is public; dataset terms should be reviewed before local download.",
        recommended_use="Benchmark reference for optional text-emotion experiments only.",
        limitations="Reddit emotion labels are not the same thing as business-review signals or internal state.",
    ),
    _source(
        id="empathetic_dialogues",
        title="EmpatheticDialogues",
        url="https://arxiv.org/abs/1811.00207",
        type="dataset",
        modality="transcript",
        category="emotion_uncertainty",
        relevance_to_signal_engine="Relevant as a contrastive dialogue corpus for empathy-like language, but not a direct fit for deterministic business review.",
        possible_labels_or_features="emotion situations, empathetic response generation",
        access_status="public",
        license_notes="Dataset reuse depends on release terms.",
        recommended_use="Reference only for future dialogue-style experiments, not as a direct product dataset.",
        limitations="Empathy generation is far from earnings-call or support-ops review workflows.",
    ),
    _source(
        id="switchboard_dialog_act_corpus",
        title="Switchboard Dialog Act Corpus",
        url="https://catalog.ldc.upenn.edu/LDC97S62",
        type="dataset",
        modality="transcript",
        category="dialogue_acts",
        relevance_to_signal_engine="Classic dialogue-act resource for Q&A turn structure, directness, and conversational move design.",
        possible_labels_or_features="statement, question, backchannel, opinion, agreement",
        access_status="license_required",
        license_notes="LDC access required.",
        recommended_use="Taxonomy and methodology reference; document metadata only unless licensed access is available.",
        limitations="License-gated and not finance-specific.",
    ),
    _source(
        id="mrda",
        title="ICSI Meeting Recorder Dialog Act Corpus (MRDA)",
        url="https://catalog.ldc.upenn.edu/LDC2004T12",
        type="dataset",
        modality="transcript",
        category="dialogue_acts",
        relevance_to_signal_engine="Useful reference for meeting-style dialogue acts, interruptions, and conversational structure.",
        possible_labels_or_features="statement, question, floor management, disruption cues",
        access_status="license_required",
        license_notes="LDC access required.",
        recommended_use="Methodology reference for dialogue-act framing and annotation guidelines.",
        limitations="Meeting domain differs materially from support, sales, and earnings calls.",
    ),
    _source(
        id="banking77",
        title="BANKING77",
        url="https://huggingface.co/datasets/PolyAI/banking77",
        type="dataset",
        modality="transcript",
        category="support_sales",
        relevance_to_signal_engine="Good intent-detection reference for finance-adjacent customer requests and support language.",
        possible_labels_or_features="banking intents, complaint categories, support actions",
        access_status="public",
        license_notes="Review dataset card before local use.",
        recommended_use="Benchmark reference for narrow-domain intent classification, especially support-style queries.",
        limitations="Short user requests do not capture multi-turn review dynamics.",
    ),
    _source(
        id="clinc150",
        title="CLINC150",
        url="https://archive.ics.uci.edu/ml/datasets/CLINC150",
        type="dataset",
        modality="transcript",
        category="support_sales",
        relevance_to_signal_engine="Intent classification baseline reference for weak-label or synthetic intent experiments.",
        possible_labels_or_features="intent classes, out-of-scope detection",
        access_status="public",
        license_notes="Use subject to UCI and original dataset terms.",
        recommended_use="Reference for intent taxonomy design and robustness checks.",
        limitations="Assistant-intent framing does not directly capture escalation, evidence, or reviewer usefulness.",
    ),
    _source(
        id="schema_guided_dialogue",
        title="Schema-Guided Dialogue dataset",
        url="https://github.com/google-research-datasets/dstc8-schema-guided-dialogue",
        type="dataset",
        modality="transcript",
        category="support_sales",
        relevance_to_signal_engine="Useful for slot/intent-oriented customer-service dialogue structure and domain-transfer thinking.",
        possible_labels_or_features="intent, slot, dialogue state, multi-domain service interactions",
        access_status="public",
        license_notes="Check repository license and data terms.",
        recommended_use="Reference for structured dialogue design and future adapter experiments.",
        limitations="Synthetic task orientation differs from real friction-heavy business conversations.",
    ),
    _source(
        id="taskmaster3",
        title="Taskmaster-3",
        url="https://ai.google.com/research/Datasets/Taskmaster",
        type="dataset",
        modality="transcript",
        category="support_sales",
        relevance_to_signal_engine="Multi-turn task-oriented dialogue reference with transactional structure closer to support and sales workflows.",
        possible_labels_or_features="task completion, intents, entity slots, follow-up commitments",
        access_status="public",
        license_notes="Review Google dataset terms before use.",
        recommended_use="Reference for future multi-turn support/sales benchmarking or schema design.",
        limitations="Task-completion success is not the same as escalation, uncertainty, or pricing friction review.",
    ),
    _source(
        id="spacy",
        title="spaCy",
        url="https://spacy.io/",
        type="library",
        modality="transcript",
        category="libraries",
        relevance_to_signal_engine="Useful optional library for tokenization, pattern matching, and lightweight rule-based NLP workflows.",
        possible_labels_or_features="tokenization, dependency patterns, named entities, custom rule pipelines",
        access_status="public",
        license_notes="See spaCy license and model-specific terms.",
        recommended_use="Optional support library for deterministic extraction and offline preprocessing.",
        limitations="Library support alone does not create validated business-review signals.",
    ),
    _source(
        id="scikit_learn",
        title="scikit-learn",
        url="https://scikit-learn.org/stable/",
        type="library",
        modality="transcript",
        category="libraries",
        relevance_to_signal_engine="Lightweight baseline-training stack for TF-IDF and classical classifiers without heavyweight models.",
        possible_labels_or_features="TF-IDF, LogisticRegression, LinearSVC, calibration, metrics",
        access_status="public",
        license_notes="BSD-style open source license.",
        recommended_use="Use for weak-label baselines and benchmark scaffolding only.",
        limitations="Classical text baselines depend heavily on label quality and task framing.",
    ),
)


MULTIMODAL_EXTRA_SOURCES: tuple[dict[str, Any], ...] = (
    _source(
        id="opensmile",
        title="openSMILE",
        url="https://audeering.github.io/opensmile-python/",
        type="library",
        modality="audio",
        category="audio",
        relevance_to_signal_engine="Classic handcrafted audio-feature extractor for bounded prosody experiments.",
        possible_labels_or_features="MFCCs, loudness, pitch, spectral descriptors, eGeMAPS",
        access_status="public",
        license_notes="Review library and feature-set licensing before commercial use.",
        recommended_use="Optional benchmark-only audio feature extraction.",
        limitations="Prosody features are review cues, not internal-state truth.",
    ),
    _source(
        id="librosa",
        title="librosa",
        url="https://librosa.org/",
        type="library",
        modality="audio",
        category="audio",
        relevance_to_signal_engine="Flexible Python audio analysis toolkit for lightweight offline feature extraction.",
        possible_labels_or_features="duration, RMS energy, tempo proxies, silence proxies, spectral features",
        access_status="public",
        license_notes="Open source library; see project license.",
        recommended_use="Optional bounded audio feature extraction when local audio is available.",
        limitations="Speech-specific interpretation still requires careful framing and validation.",
    ),
    _source(
        id="pyannote_audio",
        title="pyannote.audio",
        url="https://github.com/pyannote/pyannote-audio",
        type="tool",
        modality="audio",
        category="audio",
        relevance_to_signal_engine="Strong diarization/VAD option for future audio sidecars when licensed and cached locally.",
        possible_labels_or_features="speaker diarization, voice activity detection, segmentation",
        access_status="public",
        license_notes="Review repository, model, and Hugging Face token requirements before use.",
        recommended_use="Optional future adapter for diarization and speaker-turn recovery.",
        limitations="Often requires model downloads and tokens; not suitable for lightweight default CI.",
    ),
    _source(
        id="ravdess",
        title="RAVDESS",
        url="https://zenodo.org/records/1188976",
        type="dataset",
        modality="audio",
        category="audio",
        relevance_to_signal_engine="Common audio emotion benchmark reference for prosody experiments.",
        possible_labels_or_features="speech emotion, song emotion, intensity",
        access_status="public",
        license_notes="Review dataset terms before use.",
        recommended_use="Benchmark reference only for optional speech-emotion sidecars.",
        limitations="Acted emotion data is a poor proxy for real business conversations.",
    ),
    _source(
        id="crema_d",
        title="CREMA-D",
        url="https://huggingface.co/datasets/AbstractTTS/CREMA-D",
        type="dataset",
        modality="audio",
        category="audio",
        relevance_to_signal_engine="Speech emotion reference corpus for optional audio benchmarking.",
        possible_labels_or_features="emotion category, intensity, acted speech audio",
        access_status="public",
        license_notes="Check dataset card and original release terms.",
        recommended_use="Benchmark reference only.",
        limitations="Acted performances can overstate how separable real-world cues are.",
    ),
    _source(
        id="iemocap",
        title="IEMOCAP",
        url="https://sail.usc.edu/iemocap/",
        type="dataset",
        modality="audio",
        category="audio",
        relevance_to_signal_engine="Widely cited speech-emotion dataset with multimodal components.",
        possible_labels_or_features="emotion labels, audio, video, transcripts",
        access_status="license_required",
        license_notes="Registration and dataset agreement required.",
        recommended_use="Metadata and evaluation reference only unless access is approved.",
        limitations="Access-restricted and still based on acted or semi-scripted interactions.",
    ),
    _source(
        id="msp_podcast",
        title="MSP-Podcast",
        url="https://ecs.utdallas.edu/research/researchlabs/msp-lab/MSP-Podcast.html",
        type="dataset",
        modality="audio",
        category="audio",
        relevance_to_signal_engine="Important benchmark reference for more naturalistic speech emotion work.",
        possible_labels_or_features="emotion labels, activation, valence, speech segments",
        access_status="license_required",
        license_notes="Access terms should be reviewed before use.",
        recommended_use="Benchmark reference for later audio-sidecar evaluation design.",
        limitations="Still not a direct business-conversation review corpus.",
    ),
    _source(
        id="cmu_mosi",
        title="CMU-MOSI",
        url="http://multicomp.cs.cmu.edu/resources/cmu-mosi-dataset/",
        type="dataset",
        modality="multimodal",
        category="multimodal",
        relevance_to_signal_engine="Classic multimodal sentiment benchmark for text-audio-visual fusion references.",
        possible_labels_or_features="opinion sentiment, aligned text/audio/video segments",
        access_status="public",
        license_notes="Review dataset terms before download or reuse.",
        recommended_use="Benchmark methodology reference for late-fusion planning.",
        limitations="Opinion videos are not business-review transcripts.",
    ),
    _source(
        id="cmu_mosei",
        title="CMU-MOSEI",
        url="http://multicomp.cs.cmu.edu/resources/cmu-mosei-dataset/",
        type="dataset",
        modality="multimodal",
        category="multimodal",
        relevance_to_signal_engine="Large multimodal sentiment and emotion benchmark reference for future evaluation design.",
        possible_labels_or_features="sentiment, emotion, aligned text/audio/video",
        access_status="public",
        license_notes="Review dataset terms before use.",
        recommended_use="Methodology reference for multimodal alignment and benchmark protocol design.",
        limitations="General web-video sentiment is still far from earnings-call or support-review settings.",
    ),
    _source(
        id="meld",
        title="MELD",
        url="https://github.com/declare-lab/MELD",
        type="dataset",
        modality="multimodal",
        category="multimodal",
        relevance_to_signal_engine="Conversation-level multimodal emotion benchmark reference with speaker turns.",
        possible_labels_or_features="emotion, sentiment, dialogue turns, audio-video alignment",
        access_status="public",
        license_notes="Review repository and upstream media terms.",
        recommended_use="Reference for conversational multimodal evaluation design only.",
        limitations="TV-dialogue emotion labels do not establish reviewer usefulness in business calls.",
    ),
    _source(
        id="aff_wild2",
        title="Aff-Wild2",
        url="https://ibug.doc.ic.ac.uk/resources/aff-wild2/",
        type="benchmark",
        modality="video",
        category="video",
        relevance_to_signal_engine="High-visibility facial-behavior benchmark reference for documenting what remains optional and access-constrained.",
        possible_labels_or_features="valence-arousal, action units, expression, head pose",
        access_status="license_required",
        license_notes="Registration and benchmark access restrictions apply.",
        recommended_use="Metadata-only reference unless access is explicitly approved.",
        limitations="Benchmark framing can easily be overinterpreted; keep it out of canonical review logic.",
    ),
    _source(
        id="mediapipe",
        title="MediaPipe",
        url="https://developers.google.com/mediapipe",
        type="tool",
        modality="video",
        category="video",
        relevance_to_signal_engine="Optional local landmark and pose toolkit for bounded escalation-only video cues.",
        possible_labels_or_features="face landmarks, pose, hands, tracking",
        access_status="public",
        license_notes="See MediaPipe terms and model licenses.",
        recommended_use="Optional enhancement for local face-visibility and motion proxies on escalated cases.",
        limitations="Landmarks are not emotion truth and should stay secondary to transcript evidence.",
    ),
    _source(
        id="opencv",
        title="OpenCV",
        url="https://opencv.org/",
        type="library",
        modality="video",
        category="video",
        relevance_to_signal_engine="Lightweight frame-level statistics, motion proxies, and quality checks for optional video sidecars.",
        possible_labels_or_features="frame count, fps, brightness stats, motion proxy, detection utilities",
        access_status="public",
        license_notes="Open source library; see project license.",
        recommended_use="Optional bounded preprocessing for video quality and motion cues.",
        limitations="Generic CV features do not justify body-language certainty claims.",
    ),
)


def generated_timestamp() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat()


def nlp_research_entries() -> list[dict[str, Any]]:
    return [deepcopy(item) for item in NLP_RESEARCH_SOURCES]


def multimodal_research_entries() -> list[dict[str, Any]]:
    entries = [deepcopy(item) for item in (*NLP_RESEARCH_SOURCES, *MULTIMODAL_EXTRA_SOURCES)]
    return sorted(entries, key=lambda item: (item["modality"], item["category"], item["title"].lower()))


def build_nlp_manifest_payload() -> dict[str, Any]:
    entries = []
    for item in nlp_research_entries():
        entries.append(
            {
                "title": item["title"],
                "source_url": item["url"],
                "type": item["type"],
                "relevance_to_signal_engine": item["relevance_to_signal_engine"],
                "license_or_access_notes": f"{item['access_status']}: {item['license_notes']}",
                "downloaded_locally": item["downloaded_locally"],
                "recommended_use": item["recommended_use"],
                "limitations": item["limitations"],
                "category": item["category"],
                "modality": item["modality"],
            }
        )
    return {
        "generated_at": generated_timestamp(),
        "scope": "transcript_first_nlp_research",
        "entry_count": len(entries),
        "limitations": [
            "Manifest is a curated starting point, not an exhaustive literature review.",
            "Entries are metadata only; datasets and model artifacts were not vendored by default.",
            "Access restrictions and licensing should be rechecked before any download or training use.",
        ],
        "entries": entries,
    }


def build_multimodal_manifest_payload() -> dict[str, Any]:
    entries = []
    for item in multimodal_research_entries():
        entries.append(
            {
                "id": item["id"],
                "title": item["title"],
                "url": item["url"],
                "type": item["type"],
                "modality": item["modality"],
                "relevance_to_signal_engine": item["relevance_to_signal_engine"],
                "possible_labels_or_features": item["possible_labels_or_features"],
                "access_status": item["access_status"],
                "license_notes": item["license_notes"],
                "download_status": item["download_status"],
                "recommended_use": item["recommended_use"],
                "limitations": item["limitations"],
                "category": item["category"],
            }
        )
    return {
        "generated_at": generated_timestamp(),
        "scope": "transcript_audio_video_multimodal_research",
        "entry_count": len(entries),
        "limitations": [
            "Transcript-first deterministic outputs remain canonical.",
            "Audio and video sources are benchmark and review-cue references only.",
            "Several datasets are gated or license-restricted and are intentionally documented without local download.",
        ],
        "entries": entries,
    }


def render_nlp_manifest_markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# NLP Research Manifest",
        "",
        "This manifest is a transcript-first research map for optional benchmarking and later model experiments.",
        "",
        f"- generated_at: `{payload['generated_at']}`",
        f"- entry_count: `{payload['entry_count']}`",
        "- canonical path: deterministic transcript extraction remains the source of truth",
        "",
        "## Limitations",
        "",
    ]
    for item in payload["limitations"]:
        lines.append(f"- {item}")
    lines.extend(["", "## Entries", ""])

    by_category: dict[str, list[dict[str, Any]]] = {}
    for entry in payload["entries"]:
        by_category.setdefault(entry["category"], []).append(entry)

    for category in sorted(by_category):
        lines.append(f"### {category.replace('_', ' ').title()} (`{category}`)")
        lines.append("")
        for entry in by_category[category]:
            lines.extend(
                [
                    f"#### {entry['title']}",
                    f"- type: `{entry['type']}`",
                    f"- modality: `{entry['modality']}`",
                    f"- source: {entry['source_url']}",
                    f"- relevance: {entry['relevance_to_signal_engine']}",
                    f"- recommended use: {entry['recommended_use']}",
                    f"- access/license: {entry['license_or_access_notes']}",
                    f"- downloaded locally: `{str(entry['downloaded_locally']).lower()}`",
                    f"- limitations: {entry['limitations']}",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def render_multimodal_manifest_markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# Dataset and Research Map",
        "",
        "This map extends the transcript-first research manifest into audio, video, and multimodal references without changing canonical scoring.",
        "",
        f"- generated_at: `{payload['generated_at']}`",
        f"- entry_count: `{payload['entry_count']}`",
        "- canonical path: transcript-first deterministic extraction",
        "- optional layers: audio/video review cues, benchmark-only adapters, later fusion experiments",
        "",
        "## Limitations",
        "",
    ]
    for item in payload["limitations"]:
        lines.append(f"- {item}")

    modalities: dict[str, list[dict[str, Any]]] = {}
    for entry in payload["entries"]:
        modalities.setdefault(entry["modality"], []).append(entry)

    for modality in ("transcript", "audio", "video", "multimodal"):
        lines.extend(["", f"## {modality.title()} Sources", ""])
        for entry in modalities.get(modality, []):
            lines.extend(
                [
                    f"### {entry['title']}",
                    f"- id: `{entry['id']}`",
                    f"- type: `{entry['type']}`",
                    f"- category: `{entry['category']}`",
                    f"- url: {entry['url']}",
                    f"- relevance: {entry['relevance_to_signal_engine']}",
                    f"- labels/features: {entry['possible_labels_or_features']}",
                    f"- access: `{entry['access_status']}`",
                    f"- license notes: {entry['license_notes']}",
                    f"- download status: `{entry['download_status']}`",
                    f"- recommended use: {entry['recommended_use']}",
                    f"- limitations: {entry['limitations']}",
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


__all__ = [
    "build_multimodal_manifest_payload",
    "build_nlp_manifest_payload",
    "multimodal_research_entries",
    "nlp_research_entries",
    "render_multimodal_manifest_markdown",
    "render_nlp_manifest_markdown",
]
